// Code generated by MockGen. DO NOT EDIT.
// Source: ./ratelimiter/rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source ./ratelimiter/rate_limiter.go -destination ./tests/mock/ratelimiter/rate_limiter.go
//

// Package mock_ratelimiter is a generated GoMock package.
package mock_ratelimiter

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Limiter mocks base method.
func (m *MockInterface) Limiter() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limiter")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Limiter indicates an expected call of Limiter.
func (mr *MockInterfaceMockRecorder) Limiter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limiter", reflect.TypeOf((*MockInterface)(nil).Limiter))
}
