// Code generated by MockGen. DO NOT EDIT.
// Source: ./featureflag/feature_flag.go
//
// Generated by this command:
//
//	mockgen -source ./featureflag/feature_flag.go -destination ./tests/mock/featureflag/feature_flag.go
//

// Package mock_featureflag is a generated GoMock package.
package mock_featureflag

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// CheckUserFlags mocks base method.
func (m *MockInterface) CheckUserFlags(flagKey, userKey, userType string, value map[string]any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserFlags", flagKey, userKey, userType, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserFlags indicates an expected call of CheckUserFlags.
func (mr *MockInterfaceMockRecorder) CheckUserFlags(flagKey, userKey, userType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserFlags", reflect.TypeOf((*MockInterface)(nil).CheckUserFlags), flagKey, userKey, userType, value)
}

// GetAllUserFlags mocks base method.
func (m *MockInterface) GetAllUserFlags(userKey, userType string, value map[string]any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserFlags", userKey, userType, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserFlags indicates an expected call of GetAllUserFlags.
func (mr *MockInterfaceMockRecorder) GetAllUserFlags(userKey, userType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserFlags", reflect.TypeOf((*MockInterface)(nil).GetAllUserFlags), userKey, userType, value)
}

// Refresh mocks base method.
func (m *MockInterface) Refresh() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Refresh")
}

// Refresh indicates an expected call of Refresh.
func (mr *MockInterfaceMockRecorder) Refresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockInterface)(nil).Refresh))
}
