group:
  tech-team: "S02RK2LMJER"
  tech-be: "S038WAARMNW"
  tech-web: "S0467GZ4ENQ"
  tech-apps: "S045YF27F4N"

user:
  bambang: "U02R4THVC30"
  alvin: "U02RE316LG4"
  budiawan: "U02RBJVK342"
  peter: "U02KA7ZL49H"
  teddy: "U02KBGC29S7"
  yulia: "U02SG5NP8D8"
  rio: "U02S1AW1DFA"
  pramonow: "U039VG33FMY"
  wisnubukian98: "U03BDB9AJK1"

github:
  BamWidyat: "U02R4THVC30"
  AlvinRadeka: "U02RE316LG4"
  Budiawan7: "U02RBJVK342"
  skadinyo: "U02KA7ZL49H"
  Beelzebub0: "U02KBGC29S7"
  liaAtDelos: "U02SG5NP8D8"
  Rio-Thananu: "U02S1AW1DFA"
  pramonow: "U039VG33FMY"
  wisnubukian98: "U03BDB9AJK1"
