// Code generated by MockGen. DO NOT EDIT.
// Source: ./configbuilder/configbuilder.go
//
// Generated by this command:
//
//	mockgen -source ./configbuilder/configbuilder.go -destination ./tests/mock/configbuilder/configbuilder.go
//

// Package mock_configbuilder is a generated GoMock package.
package mock_configbuilder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// BuildConfig mocks base method.
func (m *MockInterface) BuildConfig() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildConfig")
}

// BuildConfig indicates an expected call of BuildConfig.
func (mr *MockInterfaceMockRecorder) BuildConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildConfig", reflect.TypeOf((*MockInterface)(nil).BuildConfig))
}
