// Code generated by MockGen. DO NOT EDIT.
// Source: ./parser/csv.go
//
// Generated by this command:
//
//	mockgen -source ./parser/csv.go -destination ./tests/mock/parser/csv.go
//

// Package mock_parser is a generated GoMock package.
package mock_parser

import (
	reflect "reflect"

	parser "github.com/downsized-devs/sdk-go/parser"
	gomock "go.uber.org/mock/gomock"
)

// MockCsvInterface is a mock of CsvInterface interface.
type MockCsvInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCsvInterfaceMockRecorder
}

// MockCsvInterfaceMockRecorder is the mock recorder for MockCsvInterface.
type MockCsvInterfaceMockRecorder struct {
	mock *MockCsvInterface
}

// NewMockCsvInterface creates a new mock instance.
func NewMockCsvInterface(ctrl *gomock.Controller) *MockCsvInterface {
	mock := &MockCsvInterface{ctrl: ctrl}
	mock.recorder = &MockCsvInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCsvInterface) EXPECT() *MockCsvInterfaceMockRecorder {
	return m.recorder
}

// Marshal mocks base method.
func (m *MockCsvInterface) Marshal(orig any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", orig)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockCsvInterfaceMockRecorder) Marshal(orig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockCsvInterface)(nil).Marshal), orig)
}

// MarshalWithoutHeaders mocks base method.
func (m *MockCsvInterface) MarshalWithoutHeaders(orig any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalWithoutHeaders", orig)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalWithoutHeaders indicates an expected call of MarshalWithoutHeaders.
func (mr *MockCsvInterfaceMockRecorder) MarshalWithoutHeaders(orig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalWithoutHeaders", reflect.TypeOf((*MockCsvInterface)(nil).MarshalWithoutHeaders), orig)
}

// SetOptionsRead mocks base method.
func (m *MockCsvInterface) SetOptionsRead(opt parser.CsvOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOptionsRead", opt)
}

// SetOptionsRead indicates an expected call of SetOptionsRead.
func (mr *MockCsvInterfaceMockRecorder) SetOptionsRead(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOptionsRead", reflect.TypeOf((*MockCsvInterface)(nil).SetOptionsRead), opt)
}

// SetOptionsWrite mocks base method.
func (m *MockCsvInterface) SetOptionsWrite(opt parser.CsvOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOptionsWrite", opt)
}

// SetOptionsWrite indicates an expected call of SetOptionsWrite.
func (mr *MockCsvInterfaceMockRecorder) SetOptionsWrite(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOptionsWrite", reflect.TypeOf((*MockCsvInterface)(nil).SetOptionsWrite), opt)
}

// Unmarshal mocks base method.
func (m *MockCsvInterface) Unmarshal(blob []byte, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", blob, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockCsvInterfaceMockRecorder) Unmarshal(blob, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockCsvInterface)(nil).Unmarshal), blob, dest)
}
