// Code generated by MockGen. DO NOT EDIT.
// Source: ./parser/parser.go
//
// Generated by this command:
//
//	mockgen -source ./parser/parser.go -destination ./tests/mock/parser/parser.go
//

// Package mock_parser is a generated GoMock package.
package mock_parser

import (
	reflect "reflect"

	parser "github.com/downsized-devs/sdk-go/parser"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// CsvParser mocks base method.
func (m *MockInterface) CsvParser() parser.CsvInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CsvParser")
	ret0, _ := ret[0].(parser.CsvInterface)
	return ret0
}

// CsvParser indicates an expected call of CsvParser.
func (mr *MockInterfaceMockRecorder) CsvParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CsvParser", reflect.TypeOf((*MockInterface)(nil).CsvParser))
}

// JsonParser mocks base method.
func (m *MockInterface) JsonParser() parser.JsonInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JsonParser")
	ret0, _ := ret[0].(parser.JsonInterface)
	return ret0
}

// JsonParser indicates an expected call of JsonParser.
func (mr *MockInterfaceMockRecorder) JsonParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JsonParser", reflect.TypeOf((*MockInterface)(nil).JsonParser))
}
